# Generated by Django 4.2.13 on 2024-06-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_title_4a03b1_idx',
        ),
    ]
